version: "3.7"

services:

  #### server ##############################################
  nodejs-server:
    build:
      context: ./docker
      dockerfile: nodejs.docker
    command: npm start
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - APP_PORT=${APP_PORT}
      - API_DOC_URL=${API_DOC_URL}
      - CURRENT_API_VERSION=${CURRENT_API_VERSION}
    volumes:
      - ./src:/app

  #### package-manager ##############################################
  package-manager:
    build:
      context: ./docker
      dockerfile: nodejs.docker
    command: npm
    volumes:
      - ./src:/app

